Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype ->

In [3]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(arr.shape)
print(arr.dtype)

(4, 4)
int64


Use slicing to extract the second column and the last row ->

In [10]:
print(arr[-1,1])

14


Use a boolean mask to select all values greater than the array's mean ->

In [11]:
print(arr.mean())
print(arr[arr.mean() < arr])

8.5
[ 9 10 11 12 13 14 15 16]


Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually ->

In [12]:
arr2 = np.array([[1,2,3,4]])

print(arr + arr2)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]
